Bookers/config/routes.rb
Rails.application.routes.draw do
  root to: 'bookers#top'
  resources :bookers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/booker.rb
class Booker < ApplicationRecord
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/bookers_controller.rb
class BookersController < ApplicationController
  def top
  end

  def show
    @booker = Booker.find(params[:id])
  end

  def index
    @booker = Booker.new
    @bookers = Booker.all

  end

  def create
  	booker = Booker.new(booker_params)
  	booker.save
    flash[:success] = 'Book was successfully created.'
  	redirect_to booker_path(booker.id)
  end

  def edit
    @booker = Booker.find(params[:id])
  end

  def update
    booker = Booker.find(params[:id])
    booker.update(booker_params)
    flash[:success] = 'Book was successfully updated.'
    redirect_to booker_path(booker.id)
  end

  def destroy
    booker = Booker.find(params[:id])
    booker.destroy
    flash[:success] = 'Book was successfully destroyed.'
    redirect_to bookers_path
  end

  private
  def booker_params
  	params.require(:booker).permit(:title, :body)
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/bookers_helper.rb
module BookersHelper
end

Bookers/app/views/bookers/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@booker) do |f| %>
	<p>Title</p>
	<p><%= f.text_field :title, class: "book_title" %></p>
	<p>Body</p>
	<p><%= f.text_area :body, class: "book_body" %></p>
	<p><%= f.submit 'Update Book' %></p>
	<p>
	<%= link_to "Show", booker_path(@booker), class: "show_#{@booker.id}" %> |
	<%= link_to "Back", bookers_path, class: "back" %>
	</p>
<% end %>

Bookers/app/views/bookers/index.html.erb
<p class="success_message"><%= flash[:success] %></p>
<h1>Books</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Body</th>
	</tr>

	<% @bookers.each do |booker| %>
	<tr>
		<td><%= booker.title %></td>
		<td><%= booker.body %></td>
		<td><%= link_to "Show", booker_path(booker.id), class: "show_#{booker.id}" %></td>
		<td><%= link_to "Edit", edit_booker_path(booker.id), class: "edit_#{booker.id}" %></td>
		<td><%= link_to "Destroy", booker_path(booker.id), method: :delete, class: "destroy_#{booker.id}", "data-confirm" => "Are you sure?" %></td>
	</tr>
	<% end %>
</table>

<h2>New book</h2>
<%= form_for(@booker) do |f| %>
	<p>Title</p>
	<%= f.text_field :title, class: "book_title" %>
	<p>Body</p>
	<%= f.text_area :body, class: "book_body" %>
	<p>
	<%= f.submit 'Create Book' %>
	</p>
<% end %>

Bookers/app/views/bookers/show.html.erb
<p class="success_message"><%= flash[:success] %></p>
<p><strong>Title:</strong><%= @booker.title %></p>
<p><strong>Body:</strong><%= @booker.body %></p>
<p>
<%= link_to "Edit", edit_booker_path(@booker), class: "edit_#{@booker.id}" %> |
<%= link_to "Back", bookers_path(@booker), class: "back" %>
</p>

Bookers/app/views/bookers/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や<br>印象を共有し交換することができます</p>
<p><%= link_to "start", bookers_path %></p>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>